
# Site settings
title: "naser.dev"
url: "https://naser.dev"
logo: "/assets/images/fav/android-touch-icon.png"

author: Naser
fullname: Naser Hassani
email: snhasani@gmail.com
author_twitter: snhasani
author_avatar: '/assets/images/snh_winter-avatar_grayscale.jpg'

keywords: "HTML, CSS, Javascript, React.js, React, Frontend, Opensource, Web, Software"
description: >
  A personal blog about software and programming
long_description: >
  Throughout this blog, I've tried to keep track of all that I learn each day

copyright: "Commons Attribution 4.0 International"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author: Naser
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: Naser


# Where things are
source:          ./src
destination:  ./public


# Handling Reading
encoding:       "utf-8"
include:          [".htaccess", "CNAME", "README.md"]
keep_files:     [".git", "assets"]
exclude:         ["assets", "node_modules", "gulpfile.js", "package.json", "bower.json", "webpack.config.js"]


# Conversion
markdown: kramdown


# Serving
port:    8080


# Outputting
permalink: /blog/:year/:title/
paginate_path: /blog/page:num
paginate: 5
timezone: Asia/Tehran


# Plugins
gems:
  - jalalidate
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

